Don't build netbsd because docker won't compile
The docker package gives the following error when build on netbsd:

'go' returned error: Wait error: exit status 2: # github.com/online-net/c14-cli/vendor/github.com/docker/docker/pkg/term
../../vendor/github.com/docker/docker/pkg/term/tc_other.go:12: undefined: Termios
../../vendor/github.com/docker/docker/pkg/term/tc_other.go:17: undefined: Termios